
# Diseño de software para cómputo científico

----

## Unidad 1: Modelo de objetos de Python

<small><b>Source:</b> <a href="https://dbader.org/blog/python-dunder-methods">https://dbader.org/blog/python-dunder-methods</a></small>

### Agenda de la Unidad 1
---

- Clase 1:
    - Diferencias entre alto y bajo nivel.
    - Lenguajes dinámicos y estáticos.
    
- Limbo:
    - Introducción al lenguaje Python.
    - Librerías de cómputo científico.
    
- Clase Limbo + 1 y Limbo + 2:
    - **Orientación a objetos**, decoradores.

## Python Data types
-----

- Parte de la promesas incumplidas que tengo es explicar por que esto

In [1]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

Funciona distinto de esto

In [2]:
import numpy as np

np.array([1, 2, 3]) + [4, 5, 6]

array([5, 7, 9])

## Python Data types
-----

al igual que estas dos cosas

In [3]:
np.array([1, 2, 3]) * 2

array([2, 4, 6])

In [4]:
[1, 2, 3] * 2

[1, 2, 3, 1, 2, 3]

## Python Data types
-----
O una de estas directamente no funciona

In [5]:
np.array([1, 2, 3]) + 1

array([2, 3, 4])

In [6]:
[1, 2, 3] + 1

TypeError: can only concatenate list (not "int") to list

### Dunders
----

- Por que funciona esto?

In [10]:
len([1, 3])

2

In [11]:
1 + 17

18

In [12]:
def foo():
    return "hello"

foo()  # <<< eso

'hello'

### Dunders
----

Vamos con el ejemplo siple

In [13]:
class HasLen:
    def __init__(self, l):
        self.l = l
    def __len__(self):
        return self.l

In [14]:
foo = HasLen(42)
len(foo)

42

In [15]:
foo.__len__()

42

### Dunders
----

- En Python, los métodos especiales son un conjunto de métodos predefinidos que se puede usar para enriquecer las clases. Son fáciles de reconocer porque comienzan y terminan con guiones bajos dobles, por ejemplo `__init__` o `__str__`.

- Como es cansador decir  *under-under-method-under-under* la comunidad empezo a decirles **dunder** contraccion de *double-under*.

- Los métodos Dunder le permiten emular el comportamiento de los tipos integrados. Por ejemplo, para obtener la longitud de una cadena puede llamar a `len('cadena')`.

### Dunders
----

Inicialización 

In [16]:
class Account:
    """A simple account class"""

    def __init__(self, owner, amount=0):
        """This is the constructor that lets us create
        objects from this class.
        
        """
        self.owner = owner
        self.amount = amount
        self._transactions = []
        
    def add_transaction(self, amount):
        if not isinstance(amount, int):
            raise ValueError('please use int for amount')
        self._transactions.append(amount)
        
    @property
    def balance(self):
        return self.amount + sum(self._transactions)

### Dunders
----

Representación

In [17]:
class Account(Account):

    def __repr__(self):
        return f'{self.__class__.__name__}({self.owner}, {self.amount})'

    def __str__(self):
        return f'Account of {self.owner} with starting amount: {self.amount}'

In [18]:
acc = Account('bob', 10)
acc  # repr(acc)

Account(bob, 10)

In [19]:
print(acc)  # str(acc)

Account of bob with starting amount: 10


### Dunders
----

Iteración

In [20]:
class Account(Account):

    def __len__(self):
        return len(self._transactions)

    def __getitem__(self, position):
        return self._transactions[position]

In [21]:
acc = Account('bob', 10)
acc.add_transaction(20)
acc.add_transaction(-10)
acc.add_transaction(50)
acc.add_transaction(-20)
acc.add_transaction(30)

acc.balance

80

### Dunders
----

Iteración

In [22]:
len(acc)

5

In [23]:
for t in acc:
    print(t)

20
-10
50
-20
30


In [24]:
acc[1]

-10

### Dunders
----

Comparación

Los métodos son siempre con `__` al comienzo y al final: `ge, gt, le, lt, eq, ne`
Pero a partir de `__eq__` y algun otro se pueden completar automaticamente los demas con un decorador.

In [25]:
import functools

@functools.total_ordering
class Account(Account):
    # ... (see above)

    def __eq__(self, other):
        return self.balance == other.balance

    def __lt__(self, other):
        return self.balance < other.balance

In [26]:
acc2 = Account('tim', 100)
acc2.add_transaction(20)
acc2.add_transaction(40)
acc2.balance

160

### Dunders
----

Comparación

In [27]:
acc2 > acc

True

In [28]:
acc2 == acc

False

In [29]:
acc2 >= acc

True

### Dunders
----

Aritmética

Los métodos son siempre con `__` al comienzo y al final: `add, diff, mult, div, pow`, etc.

In [30]:
class Account(Account):
    
    def __add__(self, other):
        owner = f"{self.owner} + {other.owner}"
        start_amount = self.balance + other.balance
        return Account(owner, start_amount)

In [31]:
acc2 = Account("tim", 200)
acc2.balance

200

In [32]:
acc3 = acc2 + acc
acc3.owner, acc3.balance

('tim + bob', 280)

### Dunders
----

Objetos ejecutablles/llamables/callables

In [33]:
class Account(Account):
    # ... (see above)

    def __call__(self):
        print('Start amount: {}'.format(self.amount))
        print('Transactions: ')
        for transaction in self:
            print(transaction)
        print('\nBalance: {}'.format(self.balance))

In [34]:
acc2 = Account("tim", 200)
acc2.balance

200

In [35]:
acc2()

Start amount: 200
Transactions: 

Balance: 200


Dunders Final
-------------

Hay muchos mas magic methods, pero eso se los dejo a ver segun haga falta https://rszalski.github.io/magicmethods/